//
//  CardDescriptionViewModel.swift
//  testeCVTV
//
//  Created by Douglas Stadulni on 07/05/23.
//

import Foundation
import UIKit

class CardDescriptionViewModel {

    private var allTheSpecifications: [Specs] = [
        Specs(titleCard: "The Phantom Knights of Ancient Cloak", rarity: "UR", cardImage: "cloak", typeOfCard: "Warrior / Effect", description: "If this card is in Attack Position: You can target 1 DARK monster on the field; change this card to Defense Position, and if you do, that monster gains 800 ATK/DEF until the end of your opponent's turn. You can banish this card from your GY; add 1 The Phantom Knights card from your Deck to your hand, except The Phantom Knights of Ancient Cloak. You can only use each effect of The Phantom Knights of Ancient Cloak once per turn.", numberOfAtk: "800", numberOfDef: "1000"),
        Specs(titleCard: "The Phantom Knights of Ancient Cloak", rarity: "UR", cardImage: "cloak", typeOfCard: "Warrior / Effect", description: "If this card is in Attack Position: You can target 1 DARK monster on the field; change this card to Defense Position, and if you do, that monster gains 800 ATK/DEF until the end of your opponent's turn. You can banish this card from your GY; add 1 The Phantom Knights card from your Deck to your hand, except The Phantom Knights of Ancient Cloak. You can only use each effect of The Phantom Knights of Ancient Cloak once per turn.", numberOfAtk: "800", numberOfDef: "1000"),
        Specs(titleCard: "The Phantom Knights of Ancient Cloak", rarity: "UR", cardImage: "cloak", typeOfCard: "Warrior / Effect", description: "If this card is in Attack Position: You can target 1 DARK monster on the field; change this card to Defense Position, and if you do, that monster gains 800 ATK/DEF until the end of your opponent's turn. You can banish this card from your GY; add 1 The Phantom Knights card from your Deck to your hand, except The Phantom Knights of Ancient Cloak. You can only use each effect of The Phantom Knights of Ancient Cloak once per turn.", numberOfAtk: "800", numberOfDef: "1000"),
        Specs(titleCard: "The Phantom Knights of Ragged Gloves", rarity: "UR", cardImage: "gloves", typeOfCard: "Warrior / Effect", description: "A DARK Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect. If it is Xyz Summoned: It gains 1000 ATK. You can banish this card from your GY; send 1 Phantom Knights card from your Deck to the GY. You can only use each effect of The Phantom Knights of Ragged Gloves once per turn.", numberOfAtk: "1000", numberOfDef: "500"),
        Specs(titleCard: "The Phantom Knights of Ragged Gloves", rarity: "UR", cardImage: "gloves", typeOfCard: "Warrior / Effect", description: "A DARK Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect. If it is Xyz Summoned: It gains 1000 ATK. You can banish this card from your GY; send 1 Phantom Knights card from your Deck to the GY. You can only use each effect of The Phantom Knights of Ragged Gloves once per turn.", numberOfAtk: "1000", numberOfDef: "500"),
        Specs(titleCard: "The Phantom Knights of Ragged Gloves", rarity: "UR", cardImage: "gloves", typeOfCard: "Warrior / Effect", description: "A DARK Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect. If it is Xyz Summoned: It gains 1000 ATK. You can banish this card from your GY; send 1 Phantom Knights card from your Deck to the GY. You can only use each effect of The Phantom Knights of Ragged Gloves once per turn.", numberOfAtk: "1000", numberOfDef: "500"),
        Specs(titleCard: "The Phantom Knights of Silent Boots", rarity: "SR", cardImage: "boots", typeOfCard: "Warrior / Effect", description: "If you control a The Phantom Knights monster, you can Special Summon this card (from your hand). You can only Special Summon The Phantom Knights of Silent Boots once per turn this way. You can banish this card from your GY; add 1 Phantom Knights Spell/Trap from your Deck to your hand. You can only use this effect of The Phantom Knights of Silent Boots once per turn.", numberOfAtk: "200", numberOfDef: "1200"),
        Specs(titleCard: "The Phantom Knights of Silent Boots", rarity: "SR", cardImage: "boots", typeOfCard: "Warrior / Effect", description: "If you control a The Phantom Knights monster, you can Special Summon this card (from your hand). You can only Special Summon The Phantom Knights of Silent Boots once per turn this way. You can banish this card from your GY; add 1 Phantom Knights Spell/Trap from your Deck to your hand. You can only use this effect of The Phantom Knights of Silent Boots once per turn.", numberOfAtk: "200", numberOfDef: "1200"),
        Specs(titleCard: "The Phantom Knights of Silent Boots", rarity: "SR", cardImage: "boots", typeOfCard: "Warrior / Effect", description: "If you control a The Phantom Knights monster, you can Special Summon this card (from your hand). You can only Special Summon The Phantom Knights of Silent Boots once per turn this way. You can banish this card from your GY; add 1 Phantom Knights Spell/Trap from your Deck to your hand. You can only use this effect of The Phantom Knights of Silent Boots once per turn.", numberOfAtk: "200", numberOfDef: "1200"),
        Specs(titleCard: "The Phantom Knights of Stained Greaves", rarity: "R", cardImage: "grevas", typeOfCard: "Warrior / Effect", description: "If a The Phantom Knights monster(s) is Special Summoned to your field (except during the Damage Step): You can Special Summon this card from your hand, then you can increase the Level of this card by 1. You can banish this card from your GY; Special Summon 1 The Phantom Knights monster from your hand, except The Phantom Knights of Stained Greaves, then you can increase its Level by 1. You can only use each effect of The Phantom Knights of Stained Greaves once per turn.", numberOfAtk: "1200", numberOfDef: "600"),
        Specs(titleCard: "The Phantom Knights of Stained Greaves", rarity: "R", cardImage: "grevas", typeOfCard: "Warrior / Effect", description: "If a The Phantom Knights monster(s) is Special Summoned to your field (except during the Damage Step): You can Special Summon this card from your hand, then you can increase the Level of this card by 1. You can banish this card from your GY; Special Summon 1 The Phantom Knights monster from your hand, except The Phantom Knights of Stained Greaves, then you can increase its Level by 1. You can only use each effect of The Phantom Knights of Stained Greaves once per turn.", numberOfAtk: "1200", numberOfDef: "600"),
        Specs(titleCard: "The Phantom Knights' Rank-Up-Magic Launch", rarity: "UR", cardImage: "pklaunch", typeOfCard: "Spell", description: "During the Main Phase: Target 1 DARK Xyz Monster you control with no material; Special Summon from your Extra Deck, 1 DARK Xyz Monster that is 1 Rank higher than that monster you control, by using it as the Xyz Material, and if you do, attach this card to it as additional material. (This is treated as an Xyz Summon. Transfer its materials to the Summoned monster.) During your Main Phase: You can banish this card from your GY, then target 1 DARK Xyz Monster you control; attach 1 The Phantom Knights monster from your hand to that monster as material."),
        Specs(titleCard: "Book of Moon", rarity: "UR", cardImage: "bookofmoon", typeOfCard: "Spell", description: "Target 1 face-up monster on the field; change that target to face-down Defense Position."),
        Specs(titleCard: "Book of Moon", rarity: "UR", cardImage: "lance", typeOfCard: "Spell", description: "Target 1 face-up monster on the field; until the end of this turn, that target loses 800 ATK, but is unaffected by the effects of other Spells/Traps."),
        Specs(titleCard: "Forbidden Lance", rarity: "UR", cardImage: "lance", typeOfCard: "Spell", description: "Target 1 face-up monster on the field; until the end of this turn, that target loses 800 ATK, but is unaffected by the effects of other Spells/Traps."),
        Specs(titleCard: "Mystical Space Typhoon", rarity: "UR", cardImage: "mst", typeOfCard: "Spell", description: "Target 1 Spell/Trap on the field; destroy that target."),
        Specs(titleCard: "Mystical Space Typhoon", rarity: "UR", cardImage: "mst", typeOfCard: "Spell", description: "Target 1 Spell/Trap on the field; destroy that target."),
        Specs(titleCard: "Compulsory Evacuation Device", rarity: "UR", cardImage: "compulsory", typeOfCard: "Trap", description: "Target 1 monster on the field; return that target to the hand."),
        Specs(titleCard: "Phantom Knights' Wing", rarity: "UR", cardImage: "wing", typeOfCard: "Trap", description: "Target 1 face-up monster on the field; it gains 500 ATK, also the first time that target would be destroyed by battle or card effect this turn, it is not destroyed. You can banish this card from your GY, then target 1 The Phantom Knights monster in your GY; Special Summon it, but banish it when it leaves the field. You can only use this effect of Phantom Knights' Wing once per turn."),
        Specs(titleCard: "Phantom Knights' Wing", rarity: "UR", cardImage: "wing", typeOfCard: "Trap", description: "Target 1 face-up monster on the field; it gains 500 ATK, also the first time that target would be destroyed by battle or card effect this turn, it is not destroyed. You can banish this card from your GY, then target 1 The Phantom Knights monster in your GY; Special Summon it, but banish it when it leaves the field. You can only use this effect of Phantom Knights' Wing once per turn."),
        Specs(titleCard: "Ice Dragon's Prison", rarity: "UR", cardImage: "icedragon", typeOfCard: "Trap", description: "Target 1 monster in your opponent's GY; Special Summon it to your field, but its effects are negated, then, you can banish 1 monster from both players' fields that have the same Type as each other. You can only activate 1 Ice Dragon's Prison per turn."),
        Specs(titleCard: "Ice Dragon's Prison", rarity: "UR", cardImage: "icedragon", typeOfCard: "Trap", description: "Target 1 monster in your opponent's GY; Special Summon it to your field, but its effects are negated, then, you can banish 1 monster from both players' fields that have the same Type as each other. You can only activate 1 Ice Dragon's Prison per turn."),
        Specs(titleCard: "Dark Requiem Xyz Dragon", rarity: "UR", cardImage: "requiem", typeOfCard: "Dragon / Xyz / Effect", description: "If this card has Dark Rebellion Xyz Dragon as material, it gains these effects. Once per turn: You can detach 1 material from this card, then target 1 face-up monster your opponent controls; change its ATK to 0, and if you do, this card gains ATK equal to that monster's original ATK. When your opponent activates a monster effect (Quick Effect): You can detach 1 material from this card; negate the activation, and if you do, destroy that card, then you can Special Summon 1 Xyz Monster from your GY.", numberOfAtk: "3000", numberOfDef: "2500"),
        Specs(titleCard: "Dark Rebellion Xyz Dragon", rarity: "UR", cardImage: "rebelion", typeOfCard: "Dragon / Xyz / Effect", description: "You can detach 2 materials from this card, then target 1 face-up monster your opponent controls; its ATK becomes half its current ATK, and if it does, this card gains that lost ATK.", numberOfAtk: "2500", numberOfDef: "2000"),
        Specs(titleCard: "Number 70: Malevolent Sin", rarity: "SR", cardImage: "spider", typeOfCard: "Insect / Xyz / Effect", description: "Once per turn: You can detach 1 Xyz Material from this card, then target 1 monster your opponent controls; banish it until your opponent's next Standby Phase. At the end of the Damage Step, if this card attacked: You can make this card gain 300 ATK, and if you do, increase its Rank by 3.", numberOfAtk: "2400", numberOfDef: "1200"),
        Specs(titleCard: "The Phantom Knights of Break Sword", rarity: "SR", cardImage: "sword", typeOfCard: "Warrior / Xyz / Effect", description: "Once per turn: You can detach 1 material from this card, then target 1 card you control and 1 card your opponent controls; destroy them. If this Xyz Summoned card is destroyed: You can target 2 The Phantom Knights monsters with the same Level in your GY; Special Summon them and increase their Levels by 1, also you cannot Special Summon monsters for the rest of this turn, except DARK monsters.", numberOfAtk: "2000", numberOfDef: "1000"),
        Specs(titleCard: "The Phantom Knights of Break Sword", rarity: "SR", cardImage: "sword", typeOfCard: "Warrior / Xyz / Effect", description: "Once per turn: You can detach 1 material from this card, then target 1 card you control and 1 card your opponent controls; destroy them. If this Xyz Summoned card is destroyed: You can target 2 The Phantom Knights monsters with the same Level in your GY; Special Summon them and increase their Levels by 1, also you cannot Special Summon monsters for the rest of this turn, except DARK monsters.", numberOfAtk: "2000", numberOfDef: "1000")
        ]
    
    
    func getCard(index: Int) -> Specs{
        return allTheSpecifications[index]
    }
    
    var arraySize: Int {
        return allTheSpecifications.count
    }
    
    
}
